"""added fav_animal to db

Revision ID: fbd244c68989
Revises: fb128975772a
Create Date: 2020-06-21 14:29:40.093675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbd244c68989'
down_revision = 'fb128975772a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fav_animal', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'fav_animal')
    # ### end Alembic commands ###
